# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 18:03
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('techome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techomepage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='vision'),
        ),
        migrations.AlterField(
            model_name='techomepage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='about_us'),
        ),
    ]
