# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techome', '0002_auto_20170821_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techomepage',
            old_name='intro',
            new_name='about_us',
        ),
        migrations.RenameField(
            model_name='techomepage',
            old_name='body',
            new_name='vision',
        ),
    ]
