# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 08:13
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('techome', '0003_auto_20170907_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techomepagerelatedlink',
            name='page',
        ),
        migrations.AddField(
            model_name='techomepage',
            name='related_links',
            field=wagtail.wagtailcore.fields.StreamField((('name', wagtail.wagtailcore.blocks.CharBlock(max_length=255)), ('url', wagtail.wagtailcore.blocks.URLBlock())), blank=True),
        ),
        migrations.DeleteModel(
            name='TechomePageRelatedLink',
        ),
    ]
