# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 08:17
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('techome', '0004_auto_20170907_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techomepage',
            name='related_links',
            field=wagtail.wagtailcore.fields.StreamField((('link', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(max_length=255)), ('url', wagtail.wagtailcore.blocks.URLBlock())))),), blank=True),
        ),
    ]
