# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 17:03
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='members',
            field=wagtail.wagtailcore.fields.StreamField([('Members', wagtail.wagtailcore.blocks.StructBlock([(b'dp', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'name', wagtail.wagtailcore.blocks.CharBlock()), (b'rollno', wagtail.wagtailcore.blocks.IntegerBlock()), (b'phoneno', wagtail.wagtailcore.blocks.IntegerBlock())]))]),
        ),
    ]
