# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170822_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dp',
            new_name='display_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='clubname',
        ),
        migrations.AddField(
            model_name='profile',
            name='year_in_school',
            field=models.CharField(choices=[('automobile', 'Automobile'), ('robotics', 'robotics'), ('aeromodelling', 'aeromodelling'), ('electronics', 'electronics'), ('prakriti', 'prakriti'), ('edc', 'EntrepreneurshipDevelopmentCell'), ('fnc', 'FinanceandEconomics'), ('coding', 'CodingClub'), ('astronomy', 'Astronomy'), ('acumen', 'Acumen'), ('radiog', 'RadioG')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpage',
            name='members',
            field=wagtail.wagtailcore.fields.StreamField([('Members', wagtail.wagtailcore.blocks.StructBlock([(b'display_picture', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'name', wagtail.wagtailcore.blocks.CharBlock()), (b'rollno', wagtail.wagtailcore.blocks.IntegerBlock()), (b'phoneno', wagtail.wagtailcore.blocks.IntegerBlock())]))]),
        ),
    ]
