# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170908_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='year_in_school',
            new_name='clubname',
        ),
    ]
