# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0039_collectionviewrestriction'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(max_length=250)),
                ('event', wagtail.wagtailcore.fields.StreamField([('evnt', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock()), (b'intro', wagtail.wagtailcore.blocks.RichTextBlock()), (b'start', wagtail.wagtailcore.blocks.DateTimeBlock()), (b'end', wagtail.wagtailcore.blocks.DateTimeBlock()), (b'venue', wagtail.wagtailcore.blocks.CharBlock()), (b'isActive', wagtail.wagtailcore.blocks.BooleanBlock(required=False))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
