# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='IsActive',
            new_name='is_active',
        ),
    ]
