# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 19:59
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventindexpage',
            name='event',
            field=wagtail.wagtailcore.fields.StreamField([('evnt', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock()), (b'intro', wagtail.wagtailcore.blocks.RichTextBlock()), (b'start', wagtail.wagtailcore.blocks.DateTimeBlock()), (b'end', wagtail.wagtailcore.blocks.DateTimeBlock()), (b'isActive', wagtail.wagtailcore.blocks.BooleanBlock(required=False))]))]),
        ),
    ]
