# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170924_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('intro', wagtail.wagtailcore.fields.RichTextField()),
                ('start', models.DateField(verbose_name='Start')),
                ('end', models.DateField(verbose_name='end')),
                ('venue', models.CharField(max_length=200)),
                ('IsActive', models.BooleanField()),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='eventindexpage',
            name='event',
        ),
        migrations.AddField(
            model_name='events',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.EventIndexPage'),
        ),
    ]
