# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170926_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='end',
            field=models.DateTimeField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.DateTimeField(verbose_name='Start'),
        ),
    ]
