# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0039_collectionviewrestriction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('start', models.DateField(verbose_name='startdate')),
                ('end', models.DateField(blank=True, help_text='If ongoing leave blank.', null=True, verbose_name='enddate')),
                ('intro', models.CharField(help_text='This is the context which will be in Main Projects Page', max_length=600)),
                ('body', wagtail.wagtailcore.fields.StreamField([('Descrip', wagtail.wagtailcore.blocks.RichTextBlock()), ('Images', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('Link', wagtail.wagtailcore.blocks.StructBlock([('URL', wagtail.wagtailcore.blocks.URLBlock()), ('Text', wagtail.wagtailcore.blocks.CharBlock())], icon='site')), ('Documents', wagtail.wagtaildocs.blocks.DocumentChooserBlock()), ('video', wagtail.wagtailembeds.blocks.EmbedBlock()), ('Gist', wagtail.wagtailcore.blocks.TextBlock())])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
