# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('detail', models.CharField(max_length=255)),
                ('start', models.DateField(verbose_name='Post date')),
                ('end', models.DateField(verbose_name='Post date')),
                ('body', wagtail.wagtailcore.fields.StreamField([('Descrip', wagtail.wagtailcore.blocks.RichTextBlock()), ('Images', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('Link', wagtail.wagtailcore.blocks.URLBlock()), ('Documents', wagtail.wagtaildocs.blocks.DocumentChooserBlock())])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
