# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='detail',
        ),
        migrations.AlterField(
            model_name='projects',
            name='end',
            field=models.DateField(verbose_name='enddate'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start',
            field=models.DateField(verbose_name='startdate'),
        ),
    ]
