# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170926_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='enddate'),
        ),
    ]
