# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 14:41
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170926_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('Descrip', wagtail.wagtailcore.blocks.RichTextBlock()), ('Images', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('Link', wagtail.wagtailcore.blocks.StructBlock([('URL', wagtail.wagtailcore.blocks.URLBlock()), ('Text', wagtail.wagtailcore.blocks.CharBlock())], icon='site')), ('Documents', wagtail.wagtaildocs.blocks.DocumentChooserBlock()), ('video', wagtail.wagtailembeds.blocks.EmbedBlock()), ('Gist', wagtail.wagtailcore.blocks.TextBlock())]),
        ),
    ]
