# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170926_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='intro',
            field=models.CharField(default='', help_text='This is the context which will be in Main Projects Page', max_length=600),
            preserve_default=False,
        ),
    ]
