# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projects_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='end',
            field=models.DateField(blank=True, help_text='If ongoing leave blank.', null=True, verbose_name='enddate'),
        ),
    ]
