# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementspage',
            name='competition_intro',
            field=models.CharField(max_length=600, verbose_name=b'About the Achievement'),
        ),
        migrations.AlterField(
            model_name='achievementspage',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(verbose_name=b'Decription'),
        ),
    ]
