# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 08:45
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementsindexpage',
            name='carousel',
            field=wagtail.wagtailcore.fields.StreamField([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'quotation', wagtail.wagtailcore.blocks.StructBlock([(b'text', wagtail.wagtailcore.blocks.TextBlock()), (b'author', wagtail.wagtailcore.blocks.TextBlock())])), (b'video', wagtail.wagtailembeds.blocks.EmbedBlock())], blank=True),
        ),
    ]
