# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_auto_20180206_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementsindexpage',
            name='author',
        ),
    ]
