# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_achievementspage_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementsindexpage',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
