# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_remove_achievementsindexpage_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementsindexpage',
            name='carousel',
        ),
    ]
