# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_remove_achievementsindexpage_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementspage',
            name='carousel',
            field=wagtail.wagtailcore.fields.StreamField((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('video', wagtail.wagtailembeds.blocks.EmbedBlock())), blank=True),
        ),
        migrations.AlterField(
            model_name='achievementspage',
            name='competition_intro',
            field=models.CharField(max_length=600, verbose_name='About the Achievement'),
        ),
        migrations.AlterField(
            model_name='achievementspage',
            name='date',
            field=models.DateField(verbose_name='Post date'),
        ),
        migrations.AlterField(
            model_name='achievementspage',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(verbose_name='Decription'),
        ),
    ]
