# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 18:33
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_auto_20170818_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementspage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
    ]
