# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0006_auto_20170818_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievementspage',
            old_name='intro',
            new_name='competition_intro',
        ),
        migrations.RenameField(
            model_name='achievementspage',
            old_name='body',
            new_name='description',
        ),
    ]
