# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 10:07
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0007_auto_20170907_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementspage',
            name='carousel',
            field=wagtail.wagtailcore.fields.StreamField((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('video', wagtail.wagtailembeds.blocks.EmbedBlock())), blank=True),
        ),
        migrations.AlterField(
            model_name='achievementspage',
            name='competition_intro',
            field=wagtail.wagtailcore.fields.RichTextField(verbose_name='About the Achievement'),
        ),
        migrations.AlterField(
            model_name='achievementspage',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(verbose_name='Descriptopn'),
        ),
    ]
