# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 06:08
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('images', wagtail.wagtailcore.blocks.StructBlock([('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.CharBlock())], icon='image')), ('video', wagtail.wagtailembeds.blocks.EmbedBlock())]),
        ),
    ]
