# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 15:24
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())], default=''),
            preserve_default=False,
        ),
    ]
