# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 06:14
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170926_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('video', wagtail.wagtailembeds.blocks.EmbedBlock())]),
        ),
    ]
