# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_album_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='desc',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('video', wagtail.wagtailembeds.blocks.EmbedBlock())]),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
            preserve_default=False,
        ),
    ]
