# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypage',
            name='intro',
            field=models.CharField(max_length=250),
        ),
    ]
