# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 05:58
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('images', wagtail.wagtailcore.blocks.StructBlock([('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.CharBlock())], icon='image')), ('gist', wagtail.wagtailcore.blocks.TextBlock(help_text='Go to gist.github.com to write code and copy the embed Link.')), ('Link', wagtail.wagtailcore.blocks.StructBlock([('URL', wagtail.wagtailcore.blocks.URLBlock()), ('Text', wagtail.wagtailcore.blocks.CharBlock())], icon='site')), ('quote', wagtail.wagtailcore.blocks.BlockQuoteBlock()), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock())]),
        ),
    ]
