# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20170815_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='author',
            field=models.CharField(default='Anonymous', max_length=250),
        ),
    ]
