# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 13:58
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20170928_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('images', wagtail.wagtailcore.blocks.StructBlock([('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.CharBlock(blank=True, null=True, required=False))], icon='image')), ('gist', wagtail.wagtailcore.blocks.TextBlock(help_text='Go to gist.github.com to write code and copy the embed Link.')), ('Link', wagtail.wagtailcore.blocks.StructBlock([('URL', wagtail.wagtailcore.blocks.URLBlock()), ('Text', wagtail.wagtailcore.blocks.CharBlock())], icon='site')), ('Quote', wagtail.wagtailcore.blocks.StructBlock([('quote', wagtail.wagtailcore.blocks.BlockQuoteBlock()), ('Author', wagtail.wagtailcore.blocks.TextBlock(max_length=50))], icon='quote')), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock())]),
        ),
    ]
