# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 18:28
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('clubHomePage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubhomepage',
            name='sshow',
        ),
        migrations.AddField(
            model_name='clubhomepage',
            name='AboutUs',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='clubhomepage',
            name='Vision',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='clubhomepage',
            name='slideshow',
            field=wagtail.wagtailcore.fields.StreamField([('Image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.TextBlock())]))], blank=True),
        ),
    ]
