# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubHomePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubhomepage',
            name='emailaddress',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='clubhomepage',
            name='facebook_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='clubhomepage',
            name='googleplus_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clubhomepage',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clubhomepage',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
