# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0039_collectionviewrestriction'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('slideshow', wagtail.wagtailcore.fields.StreamField([('Image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.TextBlock())]))], blank=True)),
                ('AboutUs', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('Vision', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('facebook_link', models.CharField(default='', max_length=200)),
                ('googleplus_link', models.CharField(blank=True, max_length=200)),
                ('twitter_link', models.CharField(blank=True, max_length=200)),
                ('youtube_link', models.CharField(blank=True, max_length=200)),
                ('emailaddress', models.CharField(default='', max_length=200)),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
