# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='AboutUs',
            new_name='about_us',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='emailaddress',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='facebook_link',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='googleplus_link',
            new_name='googleplus',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='twitter_link',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='Vision',
            new_name='vision',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='youtube_link',
            new_name='youtube',
        ),
    ]
