# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='carousel',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='related_links',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='vision',
        ),
        migrations.AddField(
            model_name='homepage',
            name='AboutUs',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='Vision',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='emailaddress',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facebook_link',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='googleplus_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slideshow',
            field=wagtail.wagtailcore.fields.StreamField([(b'Image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.TextBlock())]))], blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
