# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 13:07
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('club_home', '0002_auto_20180124_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubhomepage',
            name='slideshow',
            field=wagtail.wagtailcore.fields.StreamField((('Image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.TextBlock())))),), blank=True),
        ),
    ]
